# Site
name: "laoyouzi's blog"
title: "laoyouzi's blog"
description: "A maverick developer"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: ''
disqus: 'laoyouzi'
mailchimp-list:
include: ["_pages"]
permalink: /:year/:month/:title/
email: laoyouzi520@gmail.com

# Authors
authors:
  laoyouzi:
    name: laoyouzi
    display_name: laoyouzi
    avatar: 'assets/images/avatar.png'
    gravatar: bc13037f8ea7af96ccde743e6648688f
    email: laoyouzi520@gmail.com
    web: https://laoyouzi.github.io/
    twitter: 
    description: "A Chinese software engineer living and working in Xi'an."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, README.md, Gemfile, Gemfile.lock]
